QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = TestHello
TEMPLATE = app
TRANSLATIONS += lang_en.ts \  #English
                lang_zh.ts \  #Chinese
                lang_Ar.ts \  #Arabic

CONFIG += c++11

DISTFILES += \
    outside/otsCommon/CMakeLists.txt \
    outside/otsDisplayControl/CMakeLists.txt \
    outside/otsDisplayControl/otsDisplayControl.qrc.depends \
    outside/otsDisplayControl/resource/images/account-bg.png \
    outside/otsDisplayControl/resource/images/add-drop-down-normal.png \
    outside/otsDisplayControl/resource/images/add-drop-down-pressed.png \
    outside/otsDisplayControl/resource/images/anxin-logo.png \
    outside/otsDisplayControl/resource/images/arrow-right.png \
    outside/otsDisplayControl/resource/images/background.png \
    outside/otsDisplayControl/resource/images/bottom-background.png \
    outside/otsDisplayControl/resource/images/center_border.png \
    outside/otsDisplayControl/resource/images/checkbox-checked.png \
    outside/otsDisplayControl/resource/images/checkbox-unchecked.png \
    outside/otsDisplayControl/resource/images/close-button-pressed.png \
    outside/otsDisplayControl/resource/images/close_button.png \
    outside/otsDisplayControl/resource/images/down-arrow.png \
    outside/otsDisplayControl/resource/images/drop-down.png \
    outside/otsDisplayControl/resource/images/drop_down_normal.png \
    outside/otsDisplayControl/resource/images/drop_down_pressed.png \
    outside/otsDisplayControl/resource/images/layout_button_normal.png \
    outside/otsDisplayControl/resource/images/layout_button_pressed.png \
    outside/otsDisplayControl/resource/images/left_screen_button.png \
    outside/otsDisplayControl/resource/images/login-big-bg.png \
    outside/otsDisplayControl/resource/images/loginbuttonbackground.png \
    outside/otsDisplayControl/resource/images/mini_button.png \
    outside/otsDisplayControl/resource/images/minimize-button-pressed.png \
    outside/otsDisplayControl/resource/images/mirror-addbutton-hover.png \
    outside/otsDisplayControl/resource/images/mirror-addbutton-normal.png \
    outside/otsDisplayControl/resource/images/mirror-addbutton-pressed.png \
    outside/otsDisplayControl/resource/images/mirror-delbutton-hover.png \
    outside/otsDisplayControl/resource/images/mirror-delbutton-normal.png \
    outside/otsDisplayControl/resource/images/mirror-delbutton-pressed.png \
    outside/otsDisplayControl/resource/images/mirror-startbutton.png \
    outside/otsDisplayControl/resource/images/mirror-stopbutton.png \
    outside/otsDisplayControl/resource/images/mirror_button_normal.png \
    outside/otsDisplayControl/resource/images/mirror_button_pressed.png \
    outside/otsDisplayControl/resource/images/mirror_rect.png \
    outside/otsDisplayControl/resource/images/mirror_title.png \
    outside/otsDisplayControl/resource/images/model_button.png \
    outside/otsDisplayControl/resource/images/model_button_normal.png \
    outside/otsDisplayControl/resource/images/model_button_pressed.png \
    outside/otsDisplayControl/resource/images/model_title.png \
    outside/otsDisplayControl/resource/images/module-addbutton-hover.png \
    outside/otsDisplayControl/resource/images/module-addbutton-normal.png \
    outside/otsDisplayControl/resource/images/module-addbutton-pressed.png \
    outside/otsDisplayControl/resource/images/module-delbutton-hover.png \
    outside/otsDisplayControl/resource/images/module-delbutton-normal.png \
    outside/otsDisplayControl/resource/images/module-delbutton-pressed.png \
    outside/otsDisplayControl/resource/images/module-preview-start.png \
    outside/otsDisplayControl/resource/images/module-preview-stop.png \
    outside/otsDisplayControl/resource/images/poll-addbutton-hover.png \
    outside/otsDisplayControl/resource/images/poll-addbutton-normal.png \
    outside/otsDisplayControl/resource/images/poll-addbutton-pressed.png \
    outside/otsDisplayControl/resource/images/poll-delbutton-hover.png \
    outside/otsDisplayControl/resource/images/poll-delbutton-normal.png \
    outside/otsDisplayControl/resource/images/poll-delbutton-pressed.png \
    outside/otsDisplayControl/resource/images/poll-listitem-bg.png \
    outside/otsDisplayControl/resource/images/poll-startbutton.png \
    outside/otsDisplayControl/resource/images/poll-stopbutton.png \
    outside/otsDisplayControl/resource/images/poll_button_normal.png \
    outside/otsDisplayControl/resource/images/poll_button_pressed.png \
    outside/otsDisplayControl/resource/images/poll_rect.png \
    outside/otsDisplayControl/resource/images/poll_title.png \
    outside/otsDisplayControl/resource/images/preview_border.png \
    outside/otsDisplayControl/resource/images/preview_ico.png \
    outside/otsDisplayControl/resource/images/preview_left_button.png \
    outside/otsDisplayControl/resource/images/preview_right_button.png \
    outside/otsDisplayControl/resource/images/pull_button_normal.png \
    outside/otsDisplayControl/resource/images/pull_button_pressed.png \
    outside/otsDisplayControl/resource/images/pullbutton_down_normal.png \
    outside/otsDisplayControl/resource/images/pullbutton_down_pressed.png \
    outside/otsDisplayControl/resource/images/rect_3.png \
    outside/otsDisplayControl/resource/images/redo_button_disabled.png \
    outside/otsDisplayControl/resource/images/redo_button_normal.png \
    outside/otsDisplayControl/resource/images/redo_button_pressed.png \
    outside/otsDisplayControl/resource/images/remember-password-checked.png \
    outside/otsDisplayControl/resource/images/remember-password-unchecked.png \
    outside/otsDisplayControl/resource/images/right_screen_button.png \
    outside/otsDisplayControl/resource/images/round-button-normal.png \
    outside/otsDisplayControl/resource/images/round-button-pressed.png \
    outside/otsDisplayControl/resource/images/screen_button_hover.png \
    outside/otsDisplayControl/resource/images/screen_button_normal.png \
    outside/otsDisplayControl/resource/images/screen_button_pressed.png \
    outside/otsDisplayControl/resource/images/search_button.png \
    outside/otsDisplayControl/resource/images/search_button_border.png \
    outside/otsDisplayControl/resource/images/searchlineedit_border.png \
    outside/otsDisplayControl/resource/images/set_button_normal.png \
    outside/otsDisplayControl/resource/images/set_button_pressed.png \
    outside/otsDisplayControl/resource/images/signal_title_ico.png \
    outside/otsDisplayControl/resource/images/switch_button_pressed.png \
    outside/otsDisplayControl/resource/images/table-item-hover.png \
    outside/otsDisplayControl/resource/images/tree_border.png \
    outside/otsDisplayControl/resource/images/tree_branch_close.png \
    outside/otsDisplayControl/resource/images/tree_branch_open.png \
    outside/otsDisplayControl/resource/images/tree_header_icon.png \
    outside/otsDisplayControl/resource/images/undo_button_disabled.png \
    outside/otsDisplayControl/resource/images/undo_button_normal.png \
    outside/otsDisplayControl/resource/images/undo_button_pressed.png \
    outside/otsDisplayControl/resource/images/upload_button_hover.png \
    outside/otsDisplayControl/resource/images/upload_button_normal.png \
    outside/otsDisplayControl/resource/images/usericon.png \
    outside/otsDisplayControl/resource/images/userkeyicon.png \
    outside/otsLayoutModel/CMakeLists.txt \
    outside/otsManageAll/CMakeLists.txt \
    outside/otsManageAll/otsManageAll.qrc.depends \
    outside/otsManageAll/resource/images/account-bg.png \
    outside/otsManageAll/resource/images/add-drop-down-normal.png \
    outside/otsManageAll/resource/images/add-drop-down-pressed.png \
    outside/otsManageAll/resource/images/anxin-logo.png \
    outside/otsManageAll/resource/images/arrow-right.png \
    outside/otsManageAll/resource/images/background.png \
    outside/otsManageAll/resource/images/bottom-background.png \
    outside/otsManageAll/resource/images/center_border.png \
    outside/otsManageAll/resource/images/checkbox-checked.png \
    outside/otsManageAll/resource/images/checkbox-disabled.png \
    outside/otsManageAll/resource/images/checkbox-unchecked.png \
    outside/otsManageAll/resource/images/close-button-pressed.png \
    outside/otsManageAll/resource/images/close_button.png \
    outside/otsManageAll/resource/images/dialog-information.png \
    outside/otsManageAll/resource/images/dialog-warning.png \
    outside/otsManageAll/resource/images/director-room.png \
    outside/otsManageAll/resource/images/down-arrow.png \
    outside/otsManageAll/resource/images/drop-down.png \
    outside/otsManageAll/resource/images/drop_down_normal.png \
    outside/otsManageAll/resource/images/drop_down_pressed.png \
    outside/otsManageAll/resource/images/layout_button_normal.png \
    outside/otsManageAll/resource/images/layout_button_pressed.png \
    outside/otsManageAll/resource/images/left_screen_button.png \
    outside/otsManageAll/resource/images/lineedit-disable.png \
    outside/otsManageAll/resource/images/login-big-bg.png \
    outside/otsManageAll/resource/images/loginbuttonbackground.png \
    outside/otsManageAll/resource/images/mini_button.png \
    outside/otsManageAll/resource/images/minimize-button-pressed.png \
    outside/otsManageAll/resource/images/mirror-addbutton-hover.png \
    outside/otsManageAll/resource/images/mirror-addbutton-normal.png \
    outside/otsManageAll/resource/images/mirror-addbutton-pressed.png \
    outside/otsManageAll/resource/images/mirror-delbutton-hover.png \
    outside/otsManageAll/resource/images/mirror-delbutton-normal.png \
    outside/otsManageAll/resource/images/mirror-delbutton-pressed.png \
    outside/otsManageAll/resource/images/mirror-startbutton.png \
    outside/otsManageAll/resource/images/mirror-stopbutton.png \
    outside/otsManageAll/resource/images/mirror_button_normal.png \
    outside/otsManageAll/resource/images/mirror_button_pressed.png \
    outside/otsManageAll/resource/images/mirror_rect.png \
    outside/otsManageAll/resource/images/mirror_title.png \
    outside/otsManageAll/resource/images/model_button.png \
    outside/otsManageAll/resource/images/model_button_normal.png \
    outside/otsManageAll/resource/images/model_button_pressed.png \
    outside/otsManageAll/resource/images/model_title.png \
    outside/otsManageAll/resource/images/module-addbutton-hover.png \
    outside/otsManageAll/resource/images/module-addbutton-normal.png \
    outside/otsManageAll/resource/images/module-addbutton-pressed.png \
    outside/otsManageAll/resource/images/module-delbutton-hover.png \
    outside/otsManageAll/resource/images/module-delbutton-normal.png \
    outside/otsManageAll/resource/images/module-delbutton-pressed.png \
    outside/otsManageAll/resource/images/module-preview-start.png \
    outside/otsManageAll/resource/images/module-preview-stop.png \
    outside/otsManageAll/resource/images/poll-addbutton-hover.png \
    outside/otsManageAll/resource/images/poll-addbutton-normal.png \
    outside/otsManageAll/resource/images/poll-addbutton-pressed.png \
    outside/otsManageAll/resource/images/poll-delbutton-hover.png \
    outside/otsManageAll/resource/images/poll-delbutton-normal.png \
    outside/otsManageAll/resource/images/poll-delbutton-pressed.png \
    outside/otsManageAll/resource/images/poll-listitem-bg.png \
    outside/otsManageAll/resource/images/poll-startbutton.png \
    outside/otsManageAll/resource/images/poll-stopbutton.png \
    outside/otsManageAll/resource/images/poll_button_normal.png \
    outside/otsManageAll/resource/images/poll_button_pressed.png \
    outside/otsManageAll/resource/images/poll_rect.png \
    outside/otsManageAll/resource/images/poll_title.png \
    outside/otsManageAll/resource/images/preview_border.png \
    outside/otsManageAll/resource/images/preview_ico.png \
    outside/otsManageAll/resource/images/preview_left_button.png \
    outside/otsManageAll/resource/images/preview_right_button.png \
    outside/otsManageAll/resource/images/pull_button_normal.png \
    outside/otsManageAll/resource/images/pull_button_pressed.png \
    outside/otsManageAll/resource/images/pullbutton_down_normal.png \
    outside/otsManageAll/resource/images/pullbutton_down_pressed.png \
    outside/otsManageAll/resource/images/rect_3.png \
    outside/otsManageAll/resource/images/redo_button_disabled.png \
    outside/otsManageAll/resource/images/redo_button_normal.png \
    outside/otsManageAll/resource/images/redo_button_pressed.png \
    outside/otsManageAll/resource/images/remember-password-checked.png \
    outside/otsManageAll/resource/images/remember-password-unchecked.png \
    outside/otsManageAll/resource/images/right_screen_button.png \
    outside/otsManageAll/resource/images/round-button-normal.png \
    outside/otsManageAll/resource/images/round-button-pressed.png \
    outside/otsManageAll/resource/images/screen_button_hover.png \
    outside/otsManageAll/resource/images/screen_button_normal.png \
    outside/otsManageAll/resource/images/screen_button_pressed.png \
    outside/otsManageAll/resource/images/search_button.png \
    outside/otsManageAll/resource/images/search_button_border.png \
    outside/otsManageAll/resource/images/searchlineedit_border.png \
    outside/otsManageAll/resource/images/set_button_normal.png \
    outside/otsManageAll/resource/images/set_button_pressed.png \
    outside/otsManageAll/resource/images/signal_title_ico.png \
    outside/otsManageAll/resource/images/spinbox-down-normal.png \
    outside/otsManageAll/resource/images/spinbox-down-pressed.png \
    outside/otsManageAll/resource/images/spinbox-up-normal.png \
    outside/otsManageAll/resource/images/spinbox-up-pressed.png \
    outside/otsManageAll/resource/images/switch_button_pressed.png \
    outside/otsManageAll/resource/images/table-item-hover.png \
    outside/otsManageAll/resource/images/tree-item-hover.png \
    outside/otsManageAll/resource/images/tree_border.png \
    outside/otsManageAll/resource/images/tree_branch_close.png \
    outside/otsManageAll/resource/images/tree_branch_open.png \
    outside/otsManageAll/resource/images/tree_header_icon.png \
    outside/otsManageAll/resource/images/undo_button_disabled.png \
    outside/otsManageAll/resource/images/undo_button_normal.png \
    outside/otsManageAll/resource/images/undo_button_pressed.png \
    outside/otsManageAll/resource/images/upload_button_hover.png \
    outside/otsManageAll/resource/images/upload_button_normal.png \
    outside/otsManageAll/resource/images/usericon.png \
    outside/otsManageAll/resource/images/userkeyicon.png \
    outside/otsManagerMode/CMakeLists.txt \
    outside/otsPollWidget/CMakeLists.txt \
    outside/otsScreenLogin/CMakeLists.txt \
    outside/otsScreenLogin/otsScreenLogin.qrc.depends \
    outside/otsScreenLogin/resource/images/account-bg.png \
    outside/otsScreenLogin/resource/images/add-drop-down-normal.png \
    outside/otsScreenLogin/resource/images/add-drop-down-pressed.png \
    outside/otsScreenLogin/resource/images/anxin-logo.png \
    outside/otsScreenLogin/resource/images/arrow-right.png \
    outside/otsScreenLogin/resource/images/background.png \
    outside/otsScreenLogin/resource/images/bottom-background.png \
    outside/otsScreenLogin/resource/images/center_border.png \
    outside/otsScreenLogin/resource/images/checkbox-checked.png \
    outside/otsScreenLogin/resource/images/checkbox-disabled.png \
    outside/otsScreenLogin/resource/images/checkbox-unchecked.png \
    outside/otsScreenLogin/resource/images/close-button-pressed.png \
    outside/otsScreenLogin/resource/images/close_button.png \
    outside/otsScreenLogin/resource/images/dialog-information.png \
    outside/otsScreenLogin/resource/images/dialog-warning.png \
    outside/otsScreenLogin/resource/images/director-room.png \
    outside/otsScreenLogin/resource/images/down-arrow.png \
    outside/otsScreenLogin/resource/images/drop-down.png \
    outside/otsScreenLogin/resource/images/drop_down_normal.png \
    outside/otsScreenLogin/resource/images/drop_down_pressed.png \
    outside/otsScreenLogin/resource/images/layout_button_normal.png \
    outside/otsScreenLogin/resource/images/layout_button_pressed.png \
    outside/otsScreenLogin/resource/images/left_screen_button.png \
    outside/otsScreenLogin/resource/images/lineedit-disable.png \
    outside/otsScreenLogin/resource/images/login-big-bg.png \
    outside/otsScreenLogin/resource/images/loginbuttonbackground.png \
    outside/otsScreenLogin/resource/images/mini_button.png \
    outside/otsScreenLogin/resource/images/minimize-button-pressed.png \
    outside/otsScreenLogin/resource/images/mirror-addbutton-hover.png \
    outside/otsScreenLogin/resource/images/mirror-addbutton-normal.png \
    outside/otsScreenLogin/resource/images/mirror-addbutton-pressed.png \
    outside/otsScreenLogin/resource/images/mirror-delbutton-hover.png \
    outside/otsScreenLogin/resource/images/mirror-delbutton-normal.png \
    outside/otsScreenLogin/resource/images/mirror-delbutton-pressed.png \
    outside/otsScreenLogin/resource/images/mirror-startbutton.png \
    outside/otsScreenLogin/resource/images/mirror-stopbutton.png \
    outside/otsScreenLogin/resource/images/mirror_button_normal.png \
    outside/otsScreenLogin/resource/images/mirror_button_pressed.png \
    outside/otsScreenLogin/resource/images/mirror_rect.png \
    outside/otsScreenLogin/resource/images/mirror_title.png \
    outside/otsScreenLogin/resource/images/model_button.png \
    outside/otsScreenLogin/resource/images/model_button_normal.png \
    outside/otsScreenLogin/resource/images/model_button_pressed.png \
    outside/otsScreenLogin/resource/images/model_title.png \
    outside/otsScreenLogin/resource/images/module-addbutton-hover.png \
    outside/otsScreenLogin/resource/images/module-addbutton-normal.png \
    outside/otsScreenLogin/resource/images/module-addbutton-pressed.png \
    outside/otsScreenLogin/resource/images/module-delbutton-hover.png \
    outside/otsScreenLogin/resource/images/module-delbutton-normal.png \
    outside/otsScreenLogin/resource/images/module-delbutton-pressed.png \
    outside/otsScreenLogin/resource/images/module-preview-start.png \
    outside/otsScreenLogin/resource/images/module-preview-stop.png \
    outside/otsScreenLogin/resource/images/poll-addbutton-hover.png \
    outside/otsScreenLogin/resource/images/poll-addbutton-normal.png \
    outside/otsScreenLogin/resource/images/poll-addbutton-pressed.png \
    outside/otsScreenLogin/resource/images/poll-delbutton-hover.png \
    outside/otsScreenLogin/resource/images/poll-delbutton-normal.png \
    outside/otsScreenLogin/resource/images/poll-delbutton-pressed.png \
    outside/otsScreenLogin/resource/images/poll-listitem-bg.png \
    outside/otsScreenLogin/resource/images/poll-startbutton.png \
    outside/otsScreenLogin/resource/images/poll-stopbutton.png \
    outside/otsScreenLogin/resource/images/poll_button_normal.png \
    outside/otsScreenLogin/resource/images/poll_button_pressed.png \
    outside/otsScreenLogin/resource/images/poll_rect.png \
    outside/otsScreenLogin/resource/images/poll_title.png \
    outside/otsScreenLogin/resource/images/preview_border.png \
    outside/otsScreenLogin/resource/images/preview_ico.png \
    outside/otsScreenLogin/resource/images/preview_left_button.png \
    outside/otsScreenLogin/resource/images/preview_right_button.png \
    outside/otsScreenLogin/resource/images/pull_button_normal.png \
    outside/otsScreenLogin/resource/images/pull_button_pressed.png \
    outside/otsScreenLogin/resource/images/pullbutton_down_normal.png \
    outside/otsScreenLogin/resource/images/pullbutton_down_pressed.png \
    outside/otsScreenLogin/resource/images/rect_3.png \
    outside/otsScreenLogin/resource/images/redo_button_disabled.png \
    outside/otsScreenLogin/resource/images/redo_button_normal.png \
    outside/otsScreenLogin/resource/images/redo_button_pressed.png \
    outside/otsScreenLogin/resource/images/remember-password-checked.png \
    outside/otsScreenLogin/resource/images/remember-password-unchecked.png \
    outside/otsScreenLogin/resource/images/right_screen_button.png \
    outside/otsScreenLogin/resource/images/round-button-normal.png \
    outside/otsScreenLogin/resource/images/round-button-pressed.png \
    outside/otsScreenLogin/resource/images/screen_button_hover.png \
    outside/otsScreenLogin/resource/images/screen_button_normal.png \
    outside/otsScreenLogin/resource/images/screen_button_pressed.png \
    outside/otsScreenLogin/resource/images/search_button.png \
    outside/otsScreenLogin/resource/images/search_button_border.png \
    outside/otsScreenLogin/resource/images/searchlineedit_border.png \
    outside/otsScreenLogin/resource/images/set_button_normal.png \
    outside/otsScreenLogin/resource/images/set_button_pressed.png \
    outside/otsScreenLogin/resource/images/signal_title_ico.png \
    outside/otsScreenLogin/resource/images/spinbox-down-normal.png \
    outside/otsScreenLogin/resource/images/spinbox-down-pressed.png \
    outside/otsScreenLogin/resource/images/spinbox-up-normal.png \
    outside/otsScreenLogin/resource/images/spinbox-up-pressed.png \
    outside/otsScreenLogin/resource/images/switch_button_pressed.png \
    outside/otsScreenLogin/resource/images/table-item-hover.png \
    outside/otsScreenLogin/resource/images/tree-item-hover.png \
    outside/otsScreenLogin/resource/images/tree_border.png \
    outside/otsScreenLogin/resource/images/tree_branch_close.png \
    outside/otsScreenLogin/resource/images/tree_branch_open.png \
    outside/otsScreenLogin/resource/images/tree_header_icon.png \
    outside/otsScreenLogin/resource/images/undo_button_disabled.png \
    outside/otsScreenLogin/resource/images/undo_button_normal.png \
    outside/otsScreenLogin/resource/images/undo_button_pressed.png \
    outside/otsScreenLogin/resource/images/upload_button_hover.png \
    outside/otsScreenLogin/resource/images/upload_button_normal.png \
    outside/otsScreenLogin/resource/images/usericon.png \
    outside/otsScreenLogin/resource/images/userkeyicon.png \
    outside/otsScreenModel/CMakeLists.txt \
    outside/otsScreenSwitch/CMakeLists.txt \
    outside/otsScreenWidget/CMakeLists.txt \
    outside/otsSignalPreview/CMakeLists.txt \
    outside/otsSignalPreview/SignalPreview.pri \
    outside/otsSignalTree/CMakeLists.txt \
    outside/otsSignalTree/SignalTree.pri

FORMS += \
    outside/otsCommon/MessageBox.ui \
    outside/otsDisplayControl/AddMirrorWidget.ui \
    outside/otsDisplayControl/AddModelWidget.ui \
    outside/otsDisplayControl/AddPollWidget.ui \
    outside/otsDisplayControl/PreviewDialog.ui \
    outside/otsLayoutModel/LayoutModelWidget.ui \
    outside/otsLayoutModel/SetCommonLayoutDialog.ui \
    outside/otsManageAll/ConfigIPIDWidget.ui \
    outside/otsManageAll/ManageWidget.ui \
    outside/otsManageAll/Start_InitData.ui \
    outside/otsManagerMode/SignalGroupManageWidget.ui \
    outside/otsPollWidget/ChannelWidget.ui \
    outside/otsScreenLogin/ScreenLoginWidget.ui \
    outside/otsScreenModel/ScreenModelWidget.ui \
    outside/otsScreenSwitch/ScreenSwitchWidget.ui \
    outside/otsSignalPreview/SignalPreviewWidget.ui \
    outside/otsSignalTree/SignalGroupTreeWidget.ui

HEADERS += \
    outside/otsCommon/MessageBox.h \
    outside/otsDisplayControl/MainEntrance.h \
    outside/otsDisplayControl/MainWidget.h \
    outside/otsDisplayControl/OperationWidget.h \
    outside/otsLayoutModel/LayoutButton.h \
    outside/otsLayoutModel/LayoutModelWidget.h \
    outside/otsLayoutModel/MainEntrance.h \
    outside/otsLayoutModel/OperationLayoutWidget.h \
    outside/otsManageAll/ConfigIPIDWidget.h \
    outside/otsManageAll/MainEntrance.h \
    outside/otsManageAll/ManageWidget.h \
    outside/otsManageAll/Start_InitData.h \
    outside/otsManagerMode/AddAccount.h \
    outside/otsManagerMode/MainEntrance.h \
    outside/otsManagerMode/MainWidget.h \
    outside/otsManagerMode/PropertyDialog.h \
    outside/otsManagerMode/ScreenWidgetManage.h \
    outside/otsManagerMode/SignalGroupManageWidget.h \
    outside/otsManagerMode/signalgroupManagerTree.h \
    outside/otsPollWidget/MainEntrance.h \
    outside/otsPollWidget/MirrorWidget.h \
    outside/otsPollWidget/PollWidget.h \
    outside/otsScreenLogin/MainEntrance.h \
    outside/otsScreenLogin/ScreenLoginWidget.h \
    outside/otsScreenLogin/globalApi.h \
    outside/otsScreenModel/MainEntrance.h \
    outside/otsScreenModel/ScreenModelWidget.h \
    outside/otsScreenSwitch/MainEntrance.h \
    outside/otsScreenSwitch/screenswitchwidget.h \
    outside/otsScreenWidget/MainEntrance.h \
    outside/otsScreenWidget/screenlayoutwidget.h \
    outside/otsScreenWidget/screentopsplit.h \
    outside/otsScreenWidget/screenwidget.h \
    outside/otsSignalPreview/MainEntrance.h \
    outside/otsSignalPreview/previewwidget.h \
    outside/otsSignalPreview/signalpreviewwidget.h \
    outside/otsSignalTree/MainEntrance.h \
    outside/otsSignalTree/SignalGroupTreeWidget.h \
    outside/otsSignalTree/signalgrouptree.h

SOURCES += \
    main.cpp \
    outside/otsCommon/MessageBox.cpp \
    outside/otsCommon/main.cpp \
    outside/otsDisplayControl/MainEntrance.cpp \
    outside/otsDisplayControl/MainWidget.cpp \
    outside/otsDisplayControl/OperationWidget.cpp \
    outside/otsLayoutModel/LayoutButton.cpp \
    outside/otsLayoutModel/LayoutModelWidget.cpp \
    outside/otsLayoutModel/MainEntrance.cpp \
    outside/otsLayoutModel/OperationLayoutWidget.cpp \
    outside/otsManageAll/ConfigIPIDWidget.cpp \
    outside/otsManageAll/MainEntrance.cpp \
    outside/otsManageAll/ManageWidget.cpp \
    outside/otsManageAll/Start_InitData.cpp \
    outside/otsManagerMode/AddAccount.cpp \
    outside/otsManagerMode/MainEntrance.cpp \
    outside/otsManagerMode/MainWidget.cpp \
    outside/otsManagerMode/PropertyDialog.cpp \
    outside/otsManagerMode/ScreenWidgetManage.cpp \
    outside/otsManagerMode/SignalGroupManageWidget.cpp \
    outside/otsManagerMode/signalgroupManagerTree.cpp \
    outside/otsPollWidget/MainEntrance.cpp \
    outside/otsPollWidget/MirrorWidget.cpp \
    outside/otsPollWidget/PollWidget.cpp \
    outside/otsScreenLogin/MainEntrance.cpp \
    outside/otsScreenLogin/ScreenLoginWidget.cpp \
    outside/otsScreenModel/MainEntrance.cpp \
    outside/otsScreenModel/ScreenModelWidget.cpp \
    outside/otsScreenSwitch/MainEntrance.cpp \
    outside/otsScreenSwitch/screenswitchwidget.cpp \
    outside/otsScreenWidget/MainEntrance.cpp \
    outside/otsScreenWidget/screenlayoutwidget.cpp \
    outside/otsScreenWidget/screentopsplit.cpp \
    outside/otsScreenWidget/screenwidget.cpp \
    outside/otsSignalPreview/MainEntrance.cpp \
    outside/otsSignalPreview/previewwidget.cpp \
    outside/otsSignalPreview/signalpreviewwidget.cpp \
    outside/otsSignalTree/MainEntrance.cpp \
    outside/otsSignalTree/SignalGroupTreeWidget.cpp \
    outside/otsSignalTree/signalgrouptree.cpp

RESOURCES += \
    outside/otsDisplayControl/otsDisplayControl.qrc \
    outside/otsManageAll/otsManageAll.qrc \
    outside/otsScreenLogin/otsScreenLogin.qrc




